name: Build

on:
  push:
    branches: [main]
    paths: ['./index.js']
  pull_request:
    branches: [main]
    paths: ['./index.js']

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: npm install
      run: npm install

    - name: audit tools (without allow-list)
      run: npm audit --audit-level=moderate
    
    - name: ncc build
      uses: tool3/ncc@v1
      with:
        github_token: ${{ github.token }}
        src: 'index.js'
  ci:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: npm install
      run: npm install

    - name: audit tools (without allow-list)
      run: npm audit --audit-level=moderate

    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag

    - uses: actions-ecosystem/action-bump-semver@v1
      id: bump-semver
      with:
        current_version: ${{ steps.get-latest-tag.outputs.tag }}
        level: major
    
    - uses: actions-ecosystem/action-push-tag@v1
      with:
        tag: ${{ steps.bump-semver.outputs.new_version }}
        message: '${{ steps.bump-semver.outputs.new_version }}'
    
    - uses: actions-ecosystem/action-push-tag@v1
      if: ${{ github.event.pull_request.merged == true }}
      with:
        tag: ${{ steps.bump-semver.outputs.new_version }}
        message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
    
